galaxy_info:
  author: Cmdhellothere
  description: Simple role for - Prometheus, alert manager and Grafana - monotoring stack installation. For educational purposes only. Do not use for production!!!
  company: bvmspb


  license: MIT

  min_ansible_version: 2.10

  platforms:
    - name: Ubuntu
      versions:
        - 20.04


  galaxy_tags: []

dependencies: []
